### PR TITLE
feat: distribute eslint config in favor of coffeelint

### PR DESCRIPTION
**Pull request by masone**

### CODE REVIEW

**Comment by masone** [comment]
@marcbachmann as discussed

**Comment by marcbachmann** [comment]
Don't you want to keep the coffeelint config in here as long as we have some coffee-script code in the project?

**Comment by masone** [comment]
This does not delete any already copied coffeelint configs. It just removes them from being updated. I had your point in mind that you made on grunt: let's focus on the migration instead of maintaining existing stuff.

**Review by marcbachmann — APPROVED** [review]
True. You removed the files from the array and that prevents an update.

**Comment by marcbachmann** [comment]
So you removed the coffeelint file from this repo.
Do we maintain it manually in each project? Or do we re-add the file in this repo?

**Comment by masone** [comment]
I wanted to prevent it being added to every new repo where we're not using cofeescript anymore (oh my gosh this is another cry for better tooling). I did not expect any changes to that file anymore

**Pull request merged**
